
package com.nio.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NioSoaServiceImplService", targetNamespace = "http://service.nio.com/", wsdlLocation = "http://localhost:8080/NioTc4Portal/services?wsdl")
public class NioSoaServiceImplService
    extends Service
{

    private final static URL NIOSOASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NIOSOASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName NIOSOASERVICEIMPLSERVICE_QNAME = new QName("http://service.nio.com/", "NioSoaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/NioTc4Portal/services?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NIOSOASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        NIOSOASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public NioSoaServiceImplService() {
        super(__getWsdlLocation(), NIOSOASERVICEIMPLSERVICE_QNAME);
    }

    public NioSoaServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NIOSOASERVICEIMPLSERVICE_QNAME, features);
    }

    public NioSoaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, NIOSOASERVICEIMPLSERVICE_QNAME);
    }

    public NioSoaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NIOSOASERVICEIMPLSERVICE_QNAME, features);
    }

    public NioSoaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NioSoaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NioSoaService
     */
    @WebEndpoint(name = "NioSoaServiceImplPort")
    public NioSoaService getNioSoaServiceImplPort() {
        return super.getPort(new QName("http://service.nio.com/", "NioSoaServiceImplPort"), NioSoaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NioSoaService
     */
    @WebEndpoint(name = "NioSoaServiceImplPort")
    public NioSoaService getNioSoaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.nio.com/", "NioSoaServiceImplPort"), NioSoaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NIOSOASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw NIOSOASERVICEIMPLSERVICE_EXCEPTION;
        }
        return NIOSOASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
