
package com.nio.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NioSoaService", targetNamespace = "http://service.nio.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NioSoaService {


    /**
     * 
     * @param engPartID
     * @param crID
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "reviseBOMOnlyEngPart", targetNamespace = "http://service.nio.com/", className = "com.nio.service.ReviseBOMOnlyEngPart")
    @ResponseWrapper(localName = "reviseBOMOnlyEngPartResponse", targetNamespace = "http://service.nio.com/", className = "com.nio.service.ReviseBOMOnlyEngPartResponse")
    @Action(input = "http://service.nio.com/NioSoaService/reviseBOMOnlyEngPartRequest", output = "http://service.nio.com/NioSoaService/reviseBOMOnlyEngPartResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.nio.com/NioSoaService/reviseBOMOnlyEngPart/Fault/Exception")
    })
    public void reviseBOMOnlyEngPart(
        @WebParam(name = "engPartID", targetNamespace = "")
        String engPartID,
        @WebParam(name = "crID", targetNamespace = "")
        String crID)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroupAndUser", targetNamespace = "http://service.nio.com/", className = "com.nio.service.GetGroupAndUser")
    @ResponseWrapper(localName = "getGroupAndUserResponse", targetNamespace = "http://service.nio.com/", className = "com.nio.service.GetGroupAndUserResponse")
    @Action(input = "http://service.nio.com/NioSoaService/getGroupAndUserRequest", output = "http://service.nio.com/NioSoaService/getGroupAndUserResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.nio.com/NioSoaService/getGroupAndUser/Fault/Exception")
    })
    public String getGroupAndUser()
        throws Exception_Exception
    ;

    /**
     * 
     * @param status
     * @param pdfFileName
     * @param pdfFileBase64
     * @param crID
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "releaseUpdate", targetNamespace = "http://service.nio.com/", className = "com.nio.service.ReleaseUpdate")
    @ResponseWrapper(localName = "releaseUpdateResponse", targetNamespace = "http://service.nio.com/", className = "com.nio.service.ReleaseUpdateResponse")
    @Action(input = "http://service.nio.com/NioSoaService/releaseUpdateRequest", output = "http://service.nio.com/NioSoaService/releaseUpdateResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.nio.com/NioSoaService/releaseUpdate/Fault/Exception")
    })
    public void releaseUpdate(
        @WebParam(name = "crID", targetNamespace = "")
        String crID,
        @WebParam(name = "pdfFileBase64", targetNamespace = "")
        String pdfFileBase64,
        @WebParam(name = "pdfFileName", targetNamespace = "")
        String pdfFileName,
        @WebParam(name = "status", targetNamespace = "")
        String status)
        throws Exception_Exception
    ;

    /**
     * 
     * @param partType
     * @param crNum
     * @param owningUser
     * @param owningGroup
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBOMOnlyEngPart", targetNamespace = "http://service.nio.com/", className = "com.nio.service.CreateBOMOnlyEngPart")
    @ResponseWrapper(localName = "createBOMOnlyEngPartResponse", targetNamespace = "http://service.nio.com/", className = "com.nio.service.CreateBOMOnlyEngPartResponse")
    @Action(input = "http://service.nio.com/NioSoaService/createBOMOnlyEngPartRequest", output = "http://service.nio.com/NioSoaService/createBOMOnlyEngPartResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.nio.com/NioSoaService/createBOMOnlyEngPart/Fault/Exception")
    })
    public String createBOMOnlyEngPart(
        @WebParam(name = "partType", targetNamespace = "")
        String partType,
        @WebParam(name = "owning_user", targetNamespace = "")
        String owningUser,
        @WebParam(name = "owning_group", targetNamespace = "")
        String owningGroup,
        @WebParam(name = "crNum", targetNamespace = "")
        String crNum)
        throws Exception_Exception
    ;

    /**
     * 
     * @param status
     * @param crID
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "releaseCRUpdate", targetNamespace = "http://service.nio.com/", className = "com.nio.service.ReleaseCRUpdate")
    @ResponseWrapper(localName = "releaseCRUpdateResponse", targetNamespace = "http://service.nio.com/", className = "com.nio.service.ReleaseCRUpdateResponse")
    @Action(input = "http://service.nio.com/NioSoaService/releaseCRUpdateRequest", output = "http://service.nio.com/NioSoaService/releaseCRUpdateResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.nio.com/NioSoaService/releaseCRUpdate/Fault/Exception")
    })
    public void releaseCRUpdate(
        @WebParam(name = "crID", targetNamespace = "")
        String crID,
        @WebParam(name = "status", targetNamespace = "")
        String status)
        throws Exception_Exception
    ;

    /**
     * 
     * @param engPartID
     * @param crID
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "reviseENGPart", targetNamespace = "http://service.nio.com/", className = "com.nio.service.ReviseENGPart")
    @ResponseWrapper(localName = "reviseENGPartResponse", targetNamespace = "http://service.nio.com/", className = "com.nio.service.ReviseENGPartResponse")
    @Action(input = "http://service.nio.com/NioSoaService/reviseENGPartRequest", output = "http://service.nio.com/NioSoaService/reviseENGPartResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.nio.com/NioSoaService/reviseENGPart/Fault/Exception")
    })
    public void reviseENGPart(
        @WebParam(name = "engPartID", targetNamespace = "")
        String engPartID,
        @WebParam(name = "crID", targetNamespace = "")
        String crID)
        throws Exception_Exception
    ;

    /**
     * 
     * @param engPartID
     * @param crID
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isENGPartRevRelatedCADPartRev", targetNamespace = "http://service.nio.com/", className = "com.nio.service.IsENGPartRevRelatedCADPartRev")
    @ResponseWrapper(localName = "isENGPartRevRelatedCADPartRevResponse", targetNamespace = "http://service.nio.com/", className = "com.nio.service.IsENGPartRevRelatedCADPartRevResponse")
    @Action(input = "http://service.nio.com/NioSoaService/isENGPartRevRelatedCADPartRevRequest", output = "http://service.nio.com/NioSoaService/isENGPartRevRelatedCADPartRevResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.nio.com/NioSoaService/isENGPartRevRelatedCADPartRev/Fault/Exception")
    })
    public boolean isENGPartRevRelatedCADPartRev(
        @WebParam(name = "engPartID", targetNamespace = "")
        String engPartID,
        @WebParam(name = "crID", targetNamespace = "")
        String crID)
        throws Exception_Exception
    ;

}
